// background actions

export const INIT = 'INIT';

export const MATCHING_OFFERS_FOUND = 'matching_offers/FOUND';

export const RECEIVED_MATCHING_CONTEXTS = 'api/UPDATE_MATCHING_CONTEXTS';
export const RECEIVED_CRITERIA = 'api/UPDATE_CRITERIA';
export const RECEIVED_EDITORS = 'api/UPDATE_EDITORS';

export const UPDATE_DRAFT_RECOMMENDATIONS = 'UPDATE_DRAFT_RECOMMENDATIONS';

export const REFRESH_MATCHING_CONTEXTS = 'REFRESH_MATCHING_CONTEXTS';

export const INSTALLED = 'INSTALLED';

export const MATCH_CONTEXT = 'LMEM/MATCH_CONTEXT';
export const MATCH_CONTEXT_FAILURE = 'LMEM/MATCH_CONTEXT_FAILURE';
export const CONTEXT_TRIGGERED = 'LMEM/CONTEXT_TRIGGERED';
export const CONTEXT_TRIGGER_FAILURE = 'LMEM/CONTEXT_TRIGGER_FAILURE';
export const RECO_DISPLAYED = 'RECO_DISPLAYED';
export const NOTICE_IGNORED = 'NOTICE_IGNORED';

// content actions
export const NOTICES_FOUND = 'NOTICES_FOUND';
export const DISMISS_NOTICE = 'DISMISS_NOTICE';
export const UNDISMISS_NOTICE = 'UNDISMISS_NOTICE';
export const LIKE_NOTICE = 'LIKE_NOTICE';
export const UNLIKE_NOTICE = 'UNLIKE_NOTICE';
export const DISLIKE_NOTICE = 'DISLIKE_NOTICE';
export const UNDISLIKE_NOTICE = 'UNDISLIKE_NOTICE';
export const REPORT_NOTICE = 'REPORT_NOTICE';

export const INSTALLED_DETAILS = 'INSTALLED_DETAILS';

export const REDUCE_RECOMMENDATION_IFRAME = 'REDUCE_RECOMMENDATION_IFRAME';
export const EXTEND_RECOMMENDATION_IFRAME = 'EXTEND_RECOMMENDATION_IFRAME';

export const OPEN = 'OPEN';
export const OPENED = 'OPENED';
export const CLOSE = 'CLOSE';
export const CLOSED = 'CLOSED';

export const OPEN_PREFERENCE_PANEL = 'OPEN_PREFERENCE_PANEL';
export const CLOSE_PREFERENCE_PANEL = 'CLOSE_PREFERENCE_PANEL';

export const DEACTIVATED_WEBSITES = 'DEACTIVATED_WEBSITES';

export const DEACTIVATE = 'DEACTIVATE';

export const UNINSTALL = 'UNINSTALL';

export const CHECKOUT_RECO_RESOURCE_BUTTON = 'CHECKOUT_RECO_RESOURCE_BUTTON';
export const CHECKOUT_RECO_RESOURCE_LINK = 'CHECKOUT_RECO_RESOURCE_LINK';
export const CHECKOUT_RECO_ALTERNATIVE = 'CHECKOUT_RECO_ALTERNATIVE';
export const CHECKOUT_RECO_EDITOR = 'CHECKOUT_RECO_EDITOR';

export const POPUP_CLICK = 'POPUP_CLICK';

export const CRITERIA = 'CRITERIA';
export const SELECT_CRITERION = 'SELECT_CRITERION';
export const UNSELECT_CRITERION = 'UNSELECT_CRITERION';
export const EDITORS = 'EDITORS';
export const EXCLUDE_EDITOR = 'EXCLUDE_EDITOR';
export const INCLUDE_EDITOR = 'INCLUDE_EDITOR';
