// background actions
export const NOTIFY_SEND = 'notify/SEND';
export const NOTIFY_RECEIVE = 'notify/RECEIVE';

export const MATCHING_OFFERS_FOUND = 'matching_offers/FOUND';

export const RECEIVED_MATCHING_CONTEXTS = 'api/UPDATE_MATCHING_CONTEXTS';

export const HEAP_LIBRARY_TRACKED = 'heap/LIBRARY_LOADED';
export const HEAP_EVENT_TRACKED = 'heap/EVENT_TRACKED';

// content actions
export const ALTERNATIVE_FOUND = 'ALTERNATIVE_FOUND';

export const REDUCE_ALTERNATIVE_IFRAME = 'REDUCE_ALTERNATIVE_IFRAME';
export const EXTEND_ALTERNATIVE_IFRAME = 'EXTEND_ALTERNATIVE_IFRAME';

export const OPEN_PREFERENCE_PANEL = 'OPEN_PREFERENCE_PANEL';
export const CLOSE_PREFERENCE_PANEL = 'CLOSE_PREFERENCE_PANEL';

export const DEACTIVATED_WEBSITES = 'DEACTIVATED_WEBSITES';

export const DEACTIVATE = 'DEACTIVATE';
export const REACTIVATE_WEBSITE = 'REACTIVATE_WEBSITE';
