export const NOTIFY_SEND = 'notify/SEND';
export const NOTIFY_RECEIVE = 'notify/RECEIVE';

export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

export const MATCHING_OFFERS_FOUND = 'matching_offers/FOUND';
export const REMOVE_ALL_MATCHING_OFFERS = 'matching_offers/FLUSH';

export const RECEIVED_MATCHING_CONTEXTS = 'api/UPDATE_MATCHING_CONTEXTS';

// content actions
export const ALTERNATIVE_FOUND = 'ALTERNATIVE_FOUND';

export const REDUCE_ALTERNATIVE_IFRAME = 'REDUCE_ALTERNATIVE_IFRAME';
export const EXTEND_ALTERNATIVE_IFRAME = 'EXTEND_ALTERNATIVE_IFRAME';


export const HEAP_LIBRARY_TRACKED = 'heap/LIBRARY_LOADED';
export const HEAP_EVENT_TRACKED = 'heap/EVENT_TRACKED';

export const DEACTIVATE_FOR_SESSION = 'DEACTIVATE_FOR_SESSION';
export const DEACTIVATE_FOR_SOME_TIME = 'DEACTIVATE_FOR_SOME_TIME';
