// background actions
export const NOTIFY_SEND = 'notify/SEND';
export const NOTIFY_RECEIVE = 'notify/RECEIVE';

export const MATCHING_OFFERS_FOUND = 'matching_offers/FOUND';

export const RECEIVED_MATCHING_CONTEXTS = 'api/UPDATE_MATCHING_CONTEXTS';
export const RECEIVED_CRITERIA = 'api/UPDATE_CRITERIA';
export const RECEIVED_EDITORS = 'api/UPDATE_EDITORS';

export const UPDATE_DRAFT_RECOMMENDATIONS = 'UPDATE_DRAFT_RECOMMENDATIONS';

export const INSTALLED = 'INSTALLED';

export const CONTEXT_TRIGGERED = 'CONTEXT_TRIGGERED';
export const RECO_DISPLAYED = 'RECO_DISPLAYED';
export const RECO_DISMISSED = 'RECO_DISMISSED';

// content actions
export const RECOMMENDATION_FOUND = 'RECOMMENDATION_FOUND';
export const DISMISS_RECO = 'DISMISS_RECO';
export const APPROVE_RECO = 'APPROVE_RECO';
export const UNAPPROVE_RECO = 'UNAPPROVE_RECO';
export const REPORT_RECO = 'REPORT_RECO';

export const INSTALLED_DETAILS = 'INSTALLED_DETAILS';

export const REDUCE_RECOMMENDATION_IFRAME = 'REDUCE_RECOMMENDATION_IFRAME';
export const EXTEND_RECOMMENDATION_IFRAME = 'EXTEND_RECOMMENDATION_IFRAME';

export const OPEN_PREFERENCE_PANEL = 'OPEN_PREFERENCE_PANEL';
export const CLOSE_PREFERENCE_PANEL = 'CLOSE_PREFERENCE_PANEL';

export const DEACTIVATED_WEBSITES = 'DEACTIVATED_WEBSITES';

export const DEACTIVATE = 'DEACTIVATE';

export const CHECKOUT_RECO_RESOURCE = 'CHECKOUT_RECO_RESOURCE';
export const CHECKOUT_RECO_ALTERNATIVE = 'CHECKOUT_RECO_ALTERNATIVE';
export const CHECKOUT_RECO_EDITOR = 'CHECKOUT_RECO_EDITOR';

export const CRITERIA = 'CRITERIA';
export const SELECT_CRITERION = 'SELECT_CRITERION';
export const UNSELECT_CRITERION = 'UNSELECT_CRITERION';
export const EDITORS = 'EDITORS';
export const EXCLUDE_EDITOR = 'EXCLUDE_EDITOR';
export const INCLUDE_EDITOR = 'INCLUDE_EDITOR';
