environment:
  matrix:
    - nodejs_version: '4'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm@2
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install --msvs_version=2013

test_script:
  - node --version
  - npm --version
  - cmd: npm test

build: off
