POST https://api.sendinblue.com/v3/smtp/email
api-key: XXX
Content-Type: application/json

{
  "sender": { "email": "contribution@dismoi.io" },
  "to": [{ "email": "contribution@dismoi.io" }],
  "replyTo": { "email": "contribution@dismoi.io", "name":  "Jalil" },
  "subject": "Super contrib 2",
  "htmlContent": "Super contrib 2",
  "textContent": "Super contrib 2"
}

###
