export const TAB_CREATED = 'BROWSER/TAB_CREATED';
export const TAB_UPDATED = 'BROWSER/TAB_UPDATED';
export const TAB_REMOVED = 'BROWSER/TAB_REMOVED';
export const TAB_CONNECTED = 'BROWSER/TAB_CONNECTED';
